# Generated by Django 3.2.6 on 2021-09-28 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_itemoptionselection_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemoptionselection',
            name='options',
        ),
        migrations.AddField(
            model_name='itemoptionselection',
            name='options',
            field=models.JSONField(default=list),
        ),
    ]
