# Generated by Django 3.2.6 on 2021-09-29 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_itemoptionselection_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemoptionselection',
            name='item',
        ),
        migrations.AddField(
            model_name='item',
            name='options_binary',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='item',
            name='options_selection',
            field=models.JSONField(default=dict),
        ),
        migrations.DeleteModel(
            name='ItemOptionBinary',
        ),
        migrations.DeleteModel(
            name='ItemOptionSelection',
        ),
    ]
